const books = [
  {
    bookId: 1,
    title: 'Les Miserables',
    author: 'Victor Hugo',
    publisher: 'Signet',
    isbn: '978-0451419439',
    category: 'Fiction',
    classification: 'Classic',
    pageCount: 1488,
    price: 13.99,
  },
  {
    bookId: 2,
    title: 'Team of Rivals',
    author: 'Doris Kearns Goodwin',
    publisher: 'Simon & Schuster',
    isbn: '978-0743270755',
    category: 'Biography',
    classification: 'Non-Fiction',
    pageCount: 944,
    price: 14.58,
  },
  {
    bookId: 3,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    publisher: 'Mariner Books',
    isbn: '978-0547928227',
    category: 'Fiction',
    classification: 'Fantasy',
    pageCount: 304,
    price: 8.99,
  },
  {
    bookId: 4,
    title: 'Atomic Habits',
    author: 'James Clear',
    publisher: 'Avery',
    isbn: '978-0735211292',
    category: 'Self-Help',
    classification: 'Non-Fiction',
    pageCount: 320,
    price: 11.98,
  },
  {
    bookId: 5,
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    publisher: 'Simon & Schuster',
    isbn: '978-1451648539',
    category: 'Biography',
    classification: 'Non-Fiction',
    pageCount: 656,
    price: 12.79,
  },
  {
    bookId: 6,
    title: 'Clean Code',
    author: 'Robert C. Martin',
    publisher: 'Prentice Hall',
    isbn: '978-0132350884',
    category: 'Technology',
    classification: 'Non-Fiction',
    pageCount: 464,
    price: 33.24,
  },
  {
    bookId: 7,
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    publisher: 'Harper',
    isbn: '978-0062316110',
    category: 'History',
    classification: 'Non-Fiction',
    pageCount: 464,
    price: 14.99,
  },
  {
    bookId: 8,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    publisher: 'Harper Perennial',
    isbn: '978-0060935467',
    category: 'Fiction',
    classification: 'Classic',
    pageCount: 336,
    price: 7.19,
  },
  {
    bookId: 9,
    title: 'The 7 Habits of Highly Effective People',
    author: 'Stephen R. Covey',
    publisher: 'Simon & Schuster',
    isbn: '978-1982137274',
    category: 'Self-Help',
    classification: 'Non-Fiction',
    pageCount: 432,
    price: 13.79,
  },
  {
    bookId: 10,
    title: 'Educated',
    author: 'Tara Westover',
    publisher: 'Random House',
    isbn: '978-0399590504',
    category: 'Biography',
    classification: 'Non-Fiction',
    pageCount: 352,
    price: 11.39,
  },
  {
    bookId: 11,
    title: 'The Pragmatic Programmer',
    author: 'David Thomas & Andrew Hunt',
    publisher: 'Addison-Wesley',
    isbn: '978-0135957059',
    category: 'Technology',
    classification: 'Non-Fiction',
    pageCount: 352,
    price: 39.49,
  },
  {
    bookId: 12,
    title: '1776',
    author: 'David McCullough',
    publisher: 'Simon & Schuster',
    isbn: '978-0743226721',
    category: 'History',
    classification: 'Non-Fiction',
    pageCount: 386,
    price: 11.68,
  },
  {
    bookId: 13,
    title: 'Dune',
    author: 'Frank Herbert',
    publisher: 'Ace',
    isbn: '978-0441172719',
    category: 'Fiction',
    classification: 'Science Fiction',
    pageCount: 688,
    price: 9.99,
  },
  {
    bookId: 14,
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    publisher: 'TarcherPerigee',
    isbn: '978-1585424337',
    category: 'Self-Help',
    classification: 'Non-Fiction',
    pageCount: 320,
    price: 9.49,
  },
  {
    bookId: 15,
    title: 'Guns, Germs, and Steel',
    author: 'Jared Diamond',
    publisher: 'W. W. Norton',
    isbn: '978-0393354324',
    category: 'History',
    classification: 'Non-Fiction',
    pageCount: 528,
    price: 13.59,
  },
];

export default books;
