// <auto-generated />
using Bookstore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bookstore.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20260328032619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Bookstore.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Victor Hugo",
                            Category = "Fiction",
                            Classification = "Classic",
                            Isbn = "978-0451419439",
                            PageCount = 1488,
                            Price = 9.95m,
                            Publisher = "Signet",
                            Title = "Les Miserables"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Doris Kearns Goodwin",
                            Category = "Biography",
                            Classification = "Non-Fiction",
                            Isbn = "978-0743270755",
                            PageCount = 944,
                            Price = 14.58m,
                            Publisher = "Simon & Schuster",
                            Title = "Team of Rivals"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "David Thomas & Andrew Hunt",
                            Category = "Technology",
                            Classification = "Non-Fiction",
                            Isbn = "978-0135957059",
                            PageCount = 352,
                            Price = 49.99m,
                            Publisher = "Addison-Wesley",
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "James Clear",
                            Category = "Self-Help",
                            Classification = "Non-Fiction",
                            Isbn = "978-0735211292",
                            PageCount = 320,
                            Price = 11.98m,
                            Publisher = "Avery",
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Tara Westover",
                            Category = "Biography",
                            Classification = "Non-Fiction",
                            Isbn = "978-0399590504",
                            PageCount = 352,
                            Price = 12.49m,
                            Publisher = "Random House",
                            Title = "Educated"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Frank Herbert",
                            Category = "Fiction",
                            Classification = "Science Fiction",
                            Isbn = "978-0441172719",
                            PageCount = 688,
                            Price = 10.99m,
                            Publisher = "Ace",
                            Title = "Dune"
                        },
                        new
                        {
                            BookId = 7,
                            Author = "Robert C. Martin",
                            Category = "Technology",
                            Classification = "Non-Fiction",
                            Isbn = "978-0132350884",
                            PageCount = 464,
                            Price = 34.99m,
                            Publisher = "Prentice Hall",
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 8,
                            Author = "Yuval Noah Harari",
                            Category = "History",
                            Classification = "Non-Fiction",
                            Isbn = "978-0062316097",
                            PageCount = 464,
                            Price = 13.99m,
                            Publisher = "Harper",
                            Title = "Sapiens"
                        },
                        new
                        {
                            BookId = 9,
                            Author = "Stephen Hawking",
                            Category = "Science",
                            Classification = "Non-Fiction",
                            Isbn = "978-0553380163",
                            PageCount = 212,
                            Price = 10.17m,
                            Publisher = "Bantam",
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            BookId = 10,
                            Author = "Stephen R. Covey",
                            Category = "Self-Help",
                            Classification = "Non-Fiction",
                            Isbn = "978-1982137274",
                            PageCount = 432,
                            Price = 13.79m,
                            Publisher = "Simon & Schuster",
                            Title = "The 7 Habits of Highly Effective People"
                        },
                        new
                        {
                            BookId = 11,
                            Author = "George Orwell",
                            Category = "Fiction",
                            Classification = "Classic",
                            Isbn = "978-0451524935",
                            PageCount = 328,
                            Price = 7.48m,
                            Publisher = "Signet Classic",
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 12,
                            Author = "Jared Diamond",
                            Category = "History",
                            Classification = "Non-Fiction",
                            Isbn = "978-0393354324",
                            PageCount = 528,
                            Price = 14.99m,
                            Publisher = "W. W. Norton",
                            Title = "Guns, Germs, and Steel"
                        },
                        new
                        {
                            BookId = 13,
                            Author = "Walter Isaacson",
                            Category = "Biography",
                            Classification = "Non-Fiction",
                            Isbn = "978-1501127625",
                            PageCount = 656,
                            Price = 11.99m,
                            Publisher = "Simon & Schuster",
                            Title = "Steve Jobs"
                        },
                        new
                        {
                            BookId = 14,
                            Author = "Carl Sagan",
                            Category = "Science",
                            Classification = "Non-Fiction",
                            Isbn = "978-0345539434",
                            PageCount = 432,
                            Price = 12.29m,
                            Publisher = "Ballantine Books",
                            Title = "The Cosmos"
                        },
                        new
                        {
                            BookId = 15,
                            Author = "Erich Gamma et al.",
                            Category = "Technology",
                            Classification = "Non-Fiction",
                            Isbn = "978-0201633610",
                            PageCount = 416,
                            Price = 42.49m,
                            Publisher = "Addison-Wesley",
                            Title = "Design Patterns"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
